config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :profiles, only: [:show, :edit, :update]
  resources :create_user, only: [:new, :create]

  resources :chats do
    resources :messages
  end

  root "profiles#show"
  match '/profiles/get_unread_messages', to: 'profiles#unread_messages', as: 'unread_messages', via: :post
  #match 'profiles/new_user', :to => 'profiles#new_user', :as => 'new_user', :via => :post

end

app/models/chat.rb
class Chat < ActiveRecord::Base

  belongs_to :user
  has_many :messages, dependent: :destroy
  
end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user
  belongs_to :chat

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :admin]

  has_one :profile, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :messages, dependent: :destroy

  after_create :create_profile

  def create_profile
    profile = Profile.new(user_id: self.id)
    profile.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :resource, :collection

  def new
    initialize_resource
  end

  def create
    build_resource

    resorce.save!
  end

  def update
    resource.update! resource_params
  end

  def destroy
    resource.destroy!
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :find_chat, only: [:show, :edit, :update, :destroy]

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new chat_params
    @chat.first_user = current_user.id

    if @chat.save
      redirect_to @chat
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @messages = Message.where(chat_id: @chat.id).order(:updated_at)
  end

  def update
    if @chat.update chat_params
      redirect_to @chat
    else
      render 'new'
    end
  end

  def destroy
    @chat.destroy!
    redirect_to root_path
  end

  private

  def chat_params
    params.require(:chat).permit(:second_user, :name)
  end


  def find_chat
    @chat = Chat.find(params[:id])
  end

end

app/controllers/create_user_controller.rb
class CreateUserController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_chat
  before_action :set_message, only: [:update, :destroy]

  def create
    @message = Message.new message_params
    @message.user_id = current_user.id
    @message.chat_id = @chat.id

    if @message.save
      redirect_to @chat
    else
      render 'new'
    end
  end

  def new
    @message = Message.new
  end

  def destroy
    @message.destroy!
    redirect_to @chat
  end

  private

  def message_params
    params.require(:message).permit(:text)
  end

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :find_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :destroy, :update, :edit]
  before_action :show_user_chats, only: [:show, :unread_messages]

  def show
    @chats.each do |chat|
      find_unread_messages chat
    end
  end

  def edit
  end

  def update
    if @profile.update profile_params
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def unread_messages
    @chats.each do |chat|
      find_unread_messages chat
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def find_profile
    user = current_user
    @profile ||= user.profile if user != nil
  end

  def profile_params
    params.require(:profile).permit(:name, :last_name, :phone, :email, :birth)
  end

  def show_user_chats
    @chats = Chat.find_by_sql(["SELECT * FROM chats WHERE (first_user = :id OR second_user = :id)", {id: current_user.id.to_s}])
  end

  def find_unread_messages(chat)
    @messages = Message.find_by_sql(["SELECT * FROM messages WHERE (chat_id = :chat_id AND user_id != :user_id)", {chat_id: chat.id, user_id: current_user.id.to_s}])
    @unread = 0
    @messages.each do |m|
      if m.created_at.to_i > current_user.last_sign_in_at.to_i
        @unread += 1
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/chats/_form_chat.html.haml
= simple_form_for @chat do |f|
  = f.input :name, label: "Chat Name"
  = f.input :second_user, collection: User.where.not(id: current_user.id), label_method: :email, value_method: :id, label: "Select another user", include_blank: false
  %br/
  = f.button :submit, "Create Chat"

app/views/chats/edit.html.haml
%h2= 'Edit' + @chat.name
= render 'form_chat'

= link_to "Home", root_path

app/views/chats/new.html.haml
%h2 Create New Chat

= render 'form_chat'

= link_to "Home", root_path

app/views/chats/show.html.haml
%h1
  = @chat.name
.chat
  %ul
    - @messages.each do |m|
      %li
        .title= m.user.email
        %p= m.text
= render 'messages/form_sent'
%br/
.btn-group
  = link_to "Edit", edit_chat_path, class: "btn btn-default"
  = link_to "Home", root_path, class: "btn btn-default"
  = link_to "Delete", chat_path(@chat), method: :delete, class: "btn btn-danger"

app/views/create_user/new.html.haml
%h2 Sign up

= simple_form_for(@user, url: create_user_index_path(@user), html: { class: 'form-horizontal', multipart: true, method: :post }) do |f|
  = f.input :email, autofocus: true
  = f.input :password, autocomplete: "off"
  = f.input :password_confirmation, autocomplete: "off"
  = f.input :role, collection: User.roles.keys.to_a
  = f.button :submit
%br/
= link_to "Back", root_path, class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form_sent.html.haml
= simple_form_for [@chat, @chat.messages.build] do |f|
  = f.input :text, label: "Enter content", autofocus: true
  %br/
  = f.button :submit, "Send message"

app/views/messages/new.html.haml
%h1 New Message

= render 'form_sent'

app/views/profiles/_form.html.haml
= simple_form_for(@profile, html: { class: 'form-horizontal', multipart: true }) do |f|
  = f.input :name, label: "Name"
  = f.input :last_name, label: "Last Name"
  = f.input :phone, label: "Phone number"
  = f.input :email, label: "E-mail"
  = f.input :birth, label: "Birth Date"
  = f.button :submit

app/views/profiles/edit.html.haml
%h2 Edit Profile

= render 'form'

app/views/profiles/show.html.haml
.name
  %p= "Name: " + @profile.name + " " + @profile.last_name
.phone
  %p= "Phone number: " + @profile.phone.to_s
.email
  %p= "E-mail: " + current_user.email
.birth
  %p= "Birthday: " + @profile.birth.strftime("%d/%m/%Y") if @profile.birth != nil
.role
  %p= "Role: " + current_user.role
.btn-group
  = link_to "Edit My Profile", edit_profile_path(@profile), class: "btn btn-primary"
  = link_to "Exit", destroy_user_session_path, method: :delete, class: "btn btn-primary"
  = link_to "Create Chat", new_chat_path(@chat), class: "btn btn-success"

  - if current_user.admin?
    = link_to "Add new User", new_create_user_path, class: "btn btn-primary"
    = link_to "Delete this User", user_registration_path, method: :delete, class: "btn btn-primary"
    = link_to "Edit User", edit_user_registration_path, class: "btn btn-primary"
.unread
  - if @unread > 0
    %p= "You have #{@unread} messages!"
  - else
    %p You dont have new messages!
.check
  .btn.btn-default
    Check again
%h3= current_user.email + ' chats'
- if @chats.blank?
  %p You haven't chats yet!
- else
  - @chats.each do |chat|
    = link_to (chat.name), chat_path(chat)
:javascript
  $(document).on("click", '.check', function(){
    $.ajax({
      url: "#{j unread_messages_path}", // Route to the Script Controller method
      type: "POST"
      });
  });

app/views/profiles/unread_messages.js.erb
$('.unread p').remove();
$('.unread').append('<p><%= "You have #{@unread} new messages!" %></p>');